### PR TITLE
Handle empty responses

### LINKED ISSUE #21: Canceling Signature Request hangs
Hi. I sent this to support@hellosign. Nic said post the issue here so I could get notifications when it was fixed, etc, and what not. 

It would appear that the node SDK function hellosign.signatureRequest.cancel(signatureRequestId) never fires/calls the .then() or .catch() promise callbacks

I attempted one just now in debug mode and my breakpoints on either were never encountered.
When I look in the dashboard the signature request still shows "out for signature" but when when I click on it I get the error: The content you requested was not found, or you do not have permission to access it.

If I do a Postman post to https://api.hellosign.com/v3/signature_request/cancel/{signatureid}
I get back no response body but the http code is 200.

In either case, the signature request does seem to get canceled and is no longer accessible to click on from the dashboard nor from the email notification the user received. However the dashboard still shows that it is "out for signature"

So, my current issues are,
1) The HelloSign Node SDK (1.1.12) never calls/returns on the .then or .catch promise methods when canceling signature requests.
2) The dashboard shows a status of "out for signature" rather than canceled.

Thanks.

### LINKED ISSUE #50: Allow Response Handling with Delete Template Endpoint
const hellosign = require('hellosign-sdk')({ key: 'SIGN_IN_AND_CREATE_API_KEY_FIRST' });

hellosign.template.delete(templateId).then((res) => { 
// Handle response -------> NEVER GETS CALLED. 
}).catch((err) => { 
// Handle error 
});

Allow the response of 200 OK to get proper handling in the above block of code. At the moment nothing gets handled with the positive response.

### LINKED ISSUE #77: signatureRequest.cancel promise never resolves on success
hellosign-sdk version: 1.6.0 

Using the code snippet in the example: 

    hellosign.signatureRequest.cancel(request_id)
     .then(function(response){
      console.log(response.statusCode);
      console.log(response.statusMessage);
    })
    .catch(function(err){
      // Handle errors
    });

with a valid `request_id` successfully cancels the request but the promise is never resolved, in the example `console.log(response.statusCode);` and ` console.log(response.statusMessage);` are never called. An invalid `request_id` does reject the promise.

### PR DESCRIPTION
**Pull request by jacobpgn**
Currently it's not possible to `await` (or `.then`) a cancel or delete request,
eg. the following will hang indefinitely if the signature request is cancelled
successfully:
```js
await hellosign.signatureRequest.cancel(sigId)
```

This PR teaches the response handler to deal with this case and resolve/
callback, and to handle any other unexpected cases without hanging.

Successful 'cancel' requests will respond with a success status and no
content. `_responseHandler` didn't have a path for that, as it wasn't
checking for the case where the content-length header has a value of 0.

I'm not sure which cases will reach this path and have a content-length
of 1, so I've left that behaviour as it is so we don't break anything!

Resolves #77
Resolves #50
Resolves #21

### CODE REVIEW

**Comment by latoyazamill** [comment]
Hi @jacobpgn! We will have your pull request reviewed at our earliest convenience. Thank you so much for your contribution to the Node SDK!

File: lib/HelloSignResource.js [hunk 1]
```diff
@@ -188,12 +188,14 @@ HelloSignResource.prototype = {
             } else if ('content-transfer-encoding' in resHeaders && resHeaders['content-transfer-encoding'] == "binary"){
                 callback.call(self, null, res);
             // Simplified response for code-only statuses
-            } else if ('content-length' in resHeaders && resHeaders['content-length'] == "1") {
+            } else if ('content-length' in resHeaders && resHeaders['content-length'] <= "1") {
```
Comment (latoyazamill) [inline lib/HelloSignResource.js:191]: I am unsure of the previous call to have this as ==1 but I have confirmed with testing and review of the documentation that a status code of 200 will result in a Content-Type of 0. So checking for a Content-length of less than or equal to 1 will suffice in this case. This is based on initial review, still need to test functionality.

**Comment by latoyazamill** [comment]
**Confirmed that the Content-Length is 0 when you get a successful Status Code of 200 for the endpoints mentioned:**
- Cancel Incomplete Signature Request
- Delete Template

**Other endpoints to consider:** 
- Delete Team
- Remove Signature Request Access

**Note:**
- Delete API App (Checks for a status code of 204 - The server will successfully process the request, but will not returning any content). Since there is no content, then there is no reason to specify a Content-Type header.

File: lib/HelloSignResource.js (hunk 1 above)
Comment (nathanbuchar) [reply lib/HelloSignResource.js:191]: @latoyazamill do you know why we're comparing two strings here? It feels a little bit flimsy to type-convert both operands. It might be better to do something like

```
parseInt(resHeaders['content-length`], 10) <= 1
```

Where at least in this case we're making a _conscious_ effort to convert (`parseInt`) one side of the operator to be the same type as the other operand, rather than relying on the JS compiler to use its best judgement to convert both operands to numbers and hoping for the best

Comment (latoyazamill) [reply lib/HelloSignResource.js:191]: I cannot speak to this @nathanbuchar. That was before my time with the SDK. Did you want this concern to be refactored for this PR? If so, @jpescador will need to do so in order for this to be merged. If not, we can merge this PR as is (after your final review) and then we can refactor internally. Leaving this up to your best judgement. Thanks!

Comment (nathanbuchar) [reply lib/HelloSignResource.js:191]: I'm sure it's fine as-is, just wanted to note it

**Review by nathanbuchar — APPROVED** [review]

**Comment by jacobpgn** [comment]
Thank you both for reviewing and shipping a new release! 😄
